name: "Setup Gradle environment"
description: Configures an environment to run Gradle tasks
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: "17"
    - uses: gradle/gradle-build-action@v2
