name: CI
on:
  pull_request: { }
  release:
    types:
      - published
  push:
    branches:
      - develop
jobs:
  build:
    name: Run CI Steps
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      CI: true
      CIRCLE_ARTIFACTS: /tmp/ci/artifacts
      CIRCLE_TEST_REPORTS: /tmp/ci/junit
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/custom-actions/setup-gradle
      - name: build
        run: ./gradlew --parallel --stacktrace --continue check
      - name: Report gradle cache size
        run: du -hs ~/.gradle/caches
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: /tmp/ci/artifacts
          retention-days: 5

  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      CI: true
      CIRCLE_ARTIFACTS: /tmp/ci/artifacts
      CIRCLE_TEST_REPORTS: /tmp/ci/junit
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/custom-actions/setup-gradle
      - name: Publish
        run: ./gradlew --no-daemon publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          MAVEN_CENTRAL_USER: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
